/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

int init_proc();
// int puts(const char *s);
// size_t strlen(const char *s);
// int strcmp(const char *s1, const char *s2);
// int __fastcall __isoc99_scanf(_QWORD, _QWORD, _QWORD); weak
int sub_4010B0();
int sub_401120();
__int64 __fastcall sub_401160(__int64 a1, int a2);
__int64 __fastcall sub_18751A0(__int64 a1, int a2);
__int64 __fastcall sub_31B8C40(const char *a1);
__int64 __fastcall main(__int64 a1, char **a2, char **a3);
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3);
void term_proc();
// int _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *off_49C9E00)() = &sub_401150; // weak
__int64 (__fastcall *off_49C9E08)() = &sub_401120; // weak
char *s2 = "c-n|TD^zJFp|I'q\"VCj7.mNj4"; // idb
char *off_49CA050 = "f4|<eN3w$"; // weak
char byte_49CA058; // weak


//----- (0000000000401000) ----------------------------------------------------
int init_proc()
{
  int (**v0)(void); // rax@1

  v0 = &_gmon_start__;
  if ( &_gmon_start__ )
    LODWORD(v0) = _gmon_start__();
  return (unsigned __int64)v0;
}
// 49CA074: using guessed type int _gmon_start__(void);

//----- (0000000000401070) ----------------------------------------------------
#error "401076: positive sp value has been found (funcsize=3)"

//----- (00000000004010B0) ----------------------------------------------------
int sub_4010B0()
{
  char *v0; // rax@1

  v0 = &byte_49CA058;
  if ( &byte_49CA058 != &byte_49CA058 )
    LODWORD(v0) = 0;
  return (unsigned __int64)v0;
}
// 49CA058: using guessed type char byte_49CA058;

//----- (0000000000401120) ----------------------------------------------------
int sub_401120()
{
  int result; // eax@2

  if ( !byte_49CA058 )
  {
    result = sub_4010B0();
    byte_49CA058 = 1;
  }
  return result;
}
// 49CA058: using guessed type char byte_49CA058;

//----- (0000000000401160) ----------------------------------------------------
__int64 __fastcall sub_401160(__int64 a1, int a2)
{
  __int64 result; // rax@2
  __int64 v3; // [sp-8h] [bp-8h]@1

  *(&v3 - 1) = a1;
  *((_DWORD *)&v3 - 3) = a2;
  *((_DWORD *)&v3 - 5) = *((_DWORD *)&v3 - 3) / 2;
  for ( *((_DWORD *)&v3 - 6) = 0; ; ++*((_DWORD *)&v3 - 6) )
  {
    result = *((_DWORD *)&v3 - 6);
    if ( (signed int)result >= *((_DWORD *)&v3 - 5) )
      break;
    *((_BYTE *)&v3 - 13) = *(_BYTE *)(*(&v3 - 1) + *((_DWORD *)&v3 - 6));
    *(_BYTE *)(*(&v3 - 1) + *((_DWORD *)&v3 - 6)) = *(_BYTE *)(*(&v3 - 1)
                                                             + *((_DWORD *)&v3 - 3)
                                                             - 1
                                                             - *((_DWORD *)&v3 - 6));
    *(_BYTE *)(*(&v3 - 1) + *((_DWORD *)&v3 - 3) - 1 - *((_DWORD *)&v3 - 6)) = *((_BYTE *)&v3 - 13);
  }
  return result;
}

//----- (00000000018751A0) ----------------------------------------------------
__int64 __fastcall sub_18751A0(__int64 a1, int a2)
{
  __int64 result; // rax@2
  __int64 v3; // [sp-8h] [bp-8h]@1

  *(&v3 - 1) = a1;
  *((_DWORD *)&v3 - 3) = a2;
  for ( *((_DWORD *)&v3 - 4) = 0; ; ++*((_DWORD *)&v3 - 4) )
  {
    result = *((_DWORD *)&v3 - 4);
    if ( (signed int)result >= *((_DWORD *)&v3 - 3) )
      break;
    if ( (signed int)*(_BYTE *)(*(&v3 - 1) + *((_DWORD *)&v3 - 4)) > 32
      && (signed int)*(_BYTE *)(*(&v3 - 1) + *((_DWORD *)&v3 - 4)) < 127 )
    {
      *((_DWORD *)&v3 - 5) = *(_BYTE *)(*(&v3 - 1) + *((_DWORD *)&v3 - 4)) - 33;
      *(_BYTE *)(*(&v3 - 1) + *((_DWORD *)&v3 - 4)) = (off_49CA050[*((_DWORD *)&v3 - 4) % 4] - 33 + *((_DWORD *)&v3 - 5))
                                                    % 95
                                                    + 33;
    }
  }
  return result;
}
// 49CA050: using guessed type char *off_49CA050;

//----- (00000000031B8C40) ----------------------------------------------------
__int64 __fastcall sub_31B8C40(const char *a1)
{
  int v1; // ST0C_4@1
  signed int v3; // [sp-Ch] [bp-Ch]@2

  v1 = strlen(a1);
  sub_401160((__int64)a1, v1);
  sub_18751A0((__int64)a1, v1);
  if ( !strcmp(a1, s2) )
  {
    v3 = 0;
  }
  else
  {
    puts("Failed !");
    v3 = 1;
  }
  return (unsigned int)v3;
}

//----- (000000000415C1D0) ----------------------------------------------------
__int64 __fastcall main(__int64 a1, char **a2, char **a3)
{
  __int64 v4; // [sp-58h] [bp-58h]@1
  int v5; // [sp-Ch] [bp-Ch]@1

  v5 = 0;
  __isoc99_scanf("%64s", &v4, a3);
  return sub_31B8C40((const char *)&v4);
}
// 401060: using guessed type int __fastcall __isoc99_scanf(_QWORD, _QWORD, _QWORD);

//----- (00000000049C7A70) ----------------------------------------------------
void __fastcall init(unsigned int a1, __int64 a2, __int64 a3)
{
  __int64 v3; // r14@1
  signed __int64 v4; // rbp@1
  __int64 v5; // rbx@2

  v3 = a3;
  init_proc();
  v4 = &off_49C9E08 - &off_49C9E00;
  if ( v4 )
  {
    v5 = 0LL;
    do
      ((void (__fastcall *)(_QWORD, __int64, __int64))*(&off_49C9E00 + v5++))(a1, a2, v3);
    while ( v4 != v5 );
  }
}
// 49C9E00: using guessed type __int64 (__fastcall *off_49C9E00)();
// 49C9E08: using guessed type __int64 (__fastcall *off_49C9E08)();

//----- (00000000049C7AD4) ----------------------------------------------------
void term_proc()
{
  ;
}

#error "There were 1 decompilation failure(s) on 10 function(s)"
