/* This file has been generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2015 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <inttypes.h>
#include <stdio.h>
#include <string.h>

char *s2 = "c-n|TD^zJFp|I'q\"VCj7.mNj4"; // idb
char *off_49CA050 = "f4|<eN3w$"; // weak

static int64_t reverse(char * a1, int a2) {
  int64_t v3x3, v3x4, v3x5, v3x6;
  for ( v3x6 = 0; v3x6 < (a2 / 2); ++v3x6 ) {
    // swaps a1[v3x6] and a1[a2 - 1 - v3x6]
    char v3x13 = a1[v3x6];
    a1[v3x6] = a1[a2 - 1 - v3x6];
    a1[a2 - 1 - v3x6] = v3x13;
  }
  return a2 / 2;
}

static int64_t chall_crypt(char * a1, int a2) {
  int64_t v3x4, v3x5;

  for ( v3x4 = 0; v3x4 < a2; ++v3x4 )
  {
    if ( (signed int)a1[v3x4] > 32
      && (signed int)a1[v3x4] < 127 )
    {
      v3x5 = a1[v3x4] - 33;
      a1[v3x4] = (off_49CA050[v3x4 % 4] - 33 + v3x5) % 95 + 33;
    }
  }
  return a2;
}

static int chall_check(char *a1) {
  const int v1 = strlen(a1);
  int v3;

  reverse(a1, v1);
  chall_crypt(a1, v1);
  if ( !strcmp(a1, s2) ) {
    puts("Success !");
    v3 = 0;
  } else {
    puts("Failed !");
    v3 = 1;
  }
  return v3;
}

int main(int argc, char **argv, char **env) {
  char v4[65] = {0};
  scanf("%64s", v4);
  return chall_check(v4);
}
